# Generated by Django 4.2 on 2023-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('ultimo_acceso', models.DateField(auto_now=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_staff', models.BooleanField(default=False)),
                ('esta_activo', models.BooleanField(default=False)),
                ('es_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
