# Generated by Django 4.2 on 2023-04-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='es_staff',
            new_name='is_staff',
        ),
    ]
