# Generated by Django 4.2 on 2023-04-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_rename_es_staff_cuenta_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='es_admin',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='es_superadmin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='esta_activo',
            new_name='is_superadmin',
        ),
    ]
