# Generated by Django 4.2 on 2023-04-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rename_es_admin_cuenta_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='username',
        ),
    ]
